/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.List;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.HTML;

/**
 *
 * @author Senarathna
 */
public class FlightSearchResults extends javax.swing.JInternalFrame {

    /**
     * Creates new form SelectAFlight
     */
    public FlightSearchResults() {
        initComponents();
    }
    
    public FlightSearchResults(ArrayList<String> data){
        initComponents();
       
        DefaultTableModel model = (DefaultTableModel) tableList.getModel();
        int i=0;
        for (String row : data) {
            String[] check = row.split("@");
            model.addRow(new Object[]{i++,check[0], check[1], check[2], check[3], check[4], check[5], check[6]});

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        flightIDText = new javax.swing.JTextField();
        checkFlightsBtn = new javax.swing.JButton();
        way = new javax.swing.JComboBox<>();

        jPasswordField1.setText("jPasswordField1");

        setClosable(true);
        setTitle("Flight Search Results: Found");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Available Flights");

        tableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Departure", "Arrival ", "Class Type", "Required  Doc", "Date  &  Time", "Cost(Type)", "Approximate  Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableList);

        jLabel1.setText("Selected Flight (ID)");

        checkFlightsBtn.setText("Proceed");
        checkFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFlightsBtnActionPerformed(evt);
            }
        });

        way.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One-Way", "Round Trip" }));
        way.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(flightIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(way, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkFlightsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(flightIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkFlightsBtn)
                    .addComponent(way, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFlightsBtnActionPerformed
        String email=Main_Jframe.user;
        double userbalance=Double.parseDouble(functions.get_balance(email));
        double flightbalance=Double.parseDouble(tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 6).toString());
        String flight_type=tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 3).toString();
        double discount=functions.discount(email,flight_type );
        flightbalance=flightbalance*discount;
        if (userbalance>=flightbalance) {
            String s1=tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 1).toString();
            String s2=tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 2).toString();
            String s3=tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 3).toString();
            String s4=tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 4).toString();
            String dt5=tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 5).toString();//1 Jan 2024_1:00
            String[]arraydt5=new String[2];
            arraydt5=dt5.split("_");
            String d5=arraydt5[0];
            d5=Flight.convertDate(d5);
            
            
            String t5=arraydt5[1];       
                    
                    
//            String s5=Flight.getcustomdate(Integer.parseInt(arrayd5[0]),Integer.parseInt(arrayd5[1]),Integer.parseInt(arrayd5[2]));
            double i6 = userbalance - flightbalance;
            String s7 = tableList.getModel().getValueAt(Integer.parseInt(flightIDText.getText()), 7).toString();
            String s8 = way.getSelectedItem().toString();
            try {
                functions.add_booking(Main_Jframe.user + "," + s1 + "," + s2 + "," + s8 + "," + s4 + "," + s3 + "," + d5 + ","+t5+"," + flightbalance + "," + s7
                ,email,i6);
                
                JOptionPane.showMessageDialog(null, " Success");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, " Error");
            }
        }
        else if (userbalance<flightbalance) {
            JOptionPane.showMessageDialog(null," Error in mony");
        }
        /////جبت المصاري تبع اليوزر و نبع الرحلة بدي قارنهم بالاول بعدين بدي عدل على مصاري اليوزر و اعطية انو نجح
    }//GEN-LAST:event_checkFlightsBtnActionPerformed

    private void tableListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListMouseClicked
        flightIDText.setText(tableList.getValueAt(tableList.getSelectedRow(), tableList.getSelectedColumn()).toString());
    }//GEN-LAST:event_tableListMouseClicked

    private void wayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkFlightsBtn;
    private javax.swing.JTextField flightIDText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableList;
    private javax.swing.JComboBox<String> way;
    // End of variables declaration//GEN-END:variables
}
